<!-- Modal -->
<div id="bid" class="rudolf-modal fade modal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                Заявка менеджеру
            </div>
            <div class="modal-body">
                <div class="bid-form-title">Ваши контакты</div>
                <form>
                    <div class="row">
                        <div class="bid-form-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="row">
                               <div class="col-lg-4 col-md-4">
                                   <label>Имя</label>
                                   <input type="text">
                               </div>
                               <div class="col-lg-4 col-md-4">
                                   <label>Контактный телефон</label>
                                   <input type="text">
                               </div>
                               <div class="col-lg-4 col-md-4">
                                   <label>Город</label>
                                   <input type="text">
                               </div>
                            </div>
                        </div>
                        <div class="bid-form-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="row">
                               <div class="col-lg-8 col-md-8">
                                   <label>Желаемый автомобиль</label>
                                   <input type="text">
                               </div>
                            </div>
                        </div>
                        <div class="bid-form-row col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <label>Комментарий</label>
                            <textarea>

                            </textarea>
                        </div>
                        <button type="button" class="orange-button">
                            Оправить заявку
                        </button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>