<div class="tab-content container-fluid">
    <div role="tabpanel" class="tab-pane active row" id="tab1">
        <div class="info-common-top-bg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 info-common-top-bg-left-text">
                    </div>
                    <div class="col-lg-5 col-md-5 info-common-top-bg-right-text">
                        <p>
                        </p>
                        <button class="orange-button">
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container info-common-main-box">
            <div class="row">
                <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 info-common-main-title">
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1">
                    <div class="info-common-main-box-image-bg-holder">
                        <img src="/img/icons/">
                    </div>
                    <div class="info-common-main-box-title">Не более 1 часа</div>
                    <div class="info-common-main-box-text">Вы приезжаете в салон, проходите бесплатную диагностику и юридическую проверку автомобиля, после чего эксперт по оценке озвучивает вам сумму выкупа. После вашего согласия, мы оформляем документы и вы получаете свои деньги. Форма расчета по вашему желанию — наличными в кассе или на банковский счет.</div>
                </div>
                <div class="col-lg-5 col-md-5">
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1">
                </div>
                <div class="col-lg-5 col-md-5">
                </div>
            </div>
        </div>
    </div>
</div>
