<div class="container texts">
    <div class="row">
        <div class="texts-title ol-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 col-sm-12 col-xs-12">
            <?= $this->translate("Компания");?>
        </div>
    </div>
</div>

<div class="company">
    <div class="info-common-top-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6  info-common-top-bg-left-text">
                    Rudolf AutoHaus
                </div>
                <div class="col-lg-5 col-md-5 col-sm-6 info-common-top-bg-right-text">
                    <p>
                        8 лет работы, 25 профессионалов в
                        команде, 3 направления - легковые,
                        коммерческие, мото, 500 проданных
                        авто ежегодно
                    </p>
                    <button class="orange-button">
                        Отправить заявку
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="info-common-main-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-12 info-common-main-title">
                    Наши преимущества
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-main-box-box">
                    <div class="info-common-main-box-image-bg-holder">
                        <img src="/img/icons/">
                    </div>
                    <div class="info-common-main-box-title"></div>
                    <div class="info-common-main-box-text">

                    </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-6 info-common-main-box-box">
                    <div class="info-common-main-box-image-bg-holder">
                        <img src="/img/icons/">
                    </div>
                    <div class="info-common-main-box-title"></div>
                    <div class="info-common-main-box-text">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
