<div class="container texts">
    <div class="row">
        <div class="texts-title ol-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 col-sm-12 col-xs-12">
            <?= $this->translate("Продать");?>
        </div>
        <div class="">
            <!-- Навигация -->
            <div class="col-lg-offset-1 col-md-offset-1 col-lg-10 col-md-10 col-sm-12 col-xs-12">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="active">
                        <a href="#home" aria-controls="home" role="tab" data-toggle="tab">
                            <?= $this->translate("Срочный выкуп автомобиля");?>
                        </a>


                    </li>
                    <li><a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">
                            <?= $this->translate("Обмен/Trade-In");?>
                        </a>
                    </li>
                    <li><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">
                            <?= $this->translate("Комиссионная продажа");?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
        <!-- Содержимое вкладок -->
<div class="tab-content sale-tab-content container-fluid">
    <div role="tabpanel" class="tab-pane active row" id="home">
        <div class="urgent-sale-top-bg">

            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 urgent-sale-top-bg-left-text">
                        Срочный выкуп
                    </div>
                    <div class="col-lg-5 col-md-5 urgent-sale-top-bg-right-text">
                        <p>
                            В год мы выкупаем более 300 автомобилей с пробегом.<br class="hidden-md hidden-sm hidden-xs">
                            За 8 лет работы мы научились это делать профессионально.<br class="hidden-md hidden-sm hidden-xs">
                            Благодаря тому, что наш салон расположен в Киеве,<br class="hidden-md hidden-sm hidden-xs">
                            мы оценим ваш автомобиль дороже, исходя из<br class="hidden-md hidden-sm hidden-xs">
                            хорошего спроса на поддержаные автомобили в столице.
                        </p>
                        <button class="orange-button">
                            Оправить заявку
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container urgent-sale-box">
            <div class="row">
                <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 urgent-sale-box-title">
                    Наши преимущества
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1">
                    <div class="urgent-sale-box-image-bg-holder">
                        <img src="/img/icons/ic-09.png">
                    </div>
                    <div class="urgent-sale-box-info-title">Не более 1 часа</div>
                    <div class="urgent-sale-box-info-text">Вы приезжаете в салон, проходите бесплатную диагностику и юридическую проверку автомобиля, после чего эксперт по оценке озвучивает вам сумму выкупа. После вашего согласия, мы оформляем документы и вы получаете свои деньги. Форма расчета по вашему желанию — наличными в кассе или на банковский счет.</div>
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="urgent-sale-box-image-bg-holder">
                        <img src="/img/icons/ic-01.png" style="position:relative; left: -10px;">
                    </div>
                    <div class="urgent-sale-box-info-title">Безопасно и юридически грамотно</div>
                    <div class="urgent-sale-box-info-text">Вы полностью защищены от мошеннических схем при продаже своего автомобиля. Весь процесс проходит безопасно и цивилизованно. Сразу после сделки мы прекращаем повседневную эксплуатацию автомобиля и снимаем его с учета. Вам не надо переживать за штрафы и ДТП, которые могут Вас настигнуть при продаже перекупщикам.</div>
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1">
                    <div class="urgent-sale-box-image-bg-holder">
                        <img src="/img/icons/ic-02.png" style="position:relative; left: -8px;">
                    </div>
                    <div class="urgent-sale-box-info-title">Любые марки и модели</div>
                    <div class="urgent-sale-box-info-text">Для нас нет разницы какой у вас автомобиль. Основные критерии — юридическая чистота и отсутствие серьезных аварий. Для нас не существует непрофильных марок, мы оцениваем по достоинству каждый автомобиль. Мы также выкупаем кредитные автомобили. Для этого вам не нужно самостоятельно гасить кредит — мы сделаем это за вас.</div>
                </div>
                <div class="col-lg-5 col-md-5">
                    <div class="urgent-sale-box-image-bg-holder">
                        <img src="/img/icons/ic-03.png" style="position:relative; left: -12px;">
                    </div>
                    <div class="urgent-sale-box-info-title">Обмен \ Trade-in</div>
                    <div class="urgent-sale-box-info-text">Как правило, основной причиной продажи автомобиля, является покупка другого. Мы гарантированно оценим ваш автомобиль дороже, если вы подберете у нас что-то взамен. Только в нашей компании вы можете обменять между собой мотоцикл, легковой и коммерческий автомобиль.</div>
                </div>
            </div>
        </div>
    </div>
</div>
