<?php
$this->headTitle('services-title');
$this->headMeta()
    ->appendName('description', $this->translate($section . '-meta-desc'))
    ->appendName('keywords', $this->translate($section . '-meta-keywords'));
?>
<services inline-template section='<?= $section ?>'>
<div class="container texts">
    <div class="row">
        <div class="texts-title ol-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 col-sm-12 col-xs-12">
            <?= $this->translate("Услуги");?>
        </div>
        <div class="">
            <!-- Навигация -->
            <div class="col-lg-offset-1 col-md-offset-1 col-lg-10 col-md-10 col-sm-12 col-xs-12">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="{{(section == 'credit') ? 'active' : ''}}">
                        <a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">
                            <?= $this->translate("Кредитование");?>
                        </a>
                    </li>
                    <li class="{{(section == 'insurance') ? 'active' : ''}}">
                        <a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">

                            <?= $this->translate("Cтрахование");?>
                        </a>
                    </li>
                    <li class="{{(section == 'expertise') ? 'active' : ''}}">
                        <a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">

                            <?= $this->translate("Экспертиза");?>
                        </a>
                    </li>
                    <li class="{{(section == 're-registration') ? 'active' : ''}}">
                        <a href="#tab4" aria-controls="tab4" role="tab" data-toggle="tab">

                            <?= $this->translate("Переоформление");?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
        <!-- Содержимое вкладок -->
<div class="tab-content container-fluid">

    <div role="tabpanel" class="tab-pane fade row credit" id="tab1">
        <div class="info-common-top-bg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6  info-common-top-bg-left-text">
                        Кредитование
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-top-bg-right-text">
                        <p>
                            23% наших автомобилей продается в
                            кредит. Менеджеры помогут вам
                            подобрать лучшие условия из более
                            10 банков-партнеров
                        </p>
                        <button  type="button" data-toggle="modal" data-target="#bid" class="orange-button">
                            Отправить заявку
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="info-common-main-box">
            <div class="container">
                <div class="row">
                    <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-12 info-common-main-title">
                        Наши преимущества
                    </div>
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-main-box-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-01.png" style="position:relative; left: -7px;">
                        </div>
                        <div class="info-common-main-box-title">Заявка менеджеру</div>
                        <div class="info-common-main-box-text">
                            Заполните данные и мы свяжемся с вами в течение 30 минут (с 09:00 до 21:00 без выходных).
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-main-box-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-09.png">
                        </div>
                        <div class="info-common-main-box-title">Быстро и профессионально</div>
                        <div class="info-common-main-box-text">
                            Подать заявку можно по 3-м документам и получить ответ от банка в течение 1 дня.
                        </div>
                    </div>
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-main-box-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-06.png" style="position:relative; left: 0;">
                        </div>
                        <div class="info-common-main-box-title">Покупатели из других регионов</div>
                        <div class="info-common-main-box-text">Доступно для всех видов транспорта и покупателей из любой области.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane fade row insurance" id="tab2">
        <div class="info-common-top-bg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-top-bg-left-text">
                        Страхование
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-top-bg-right-text">
                        <p>
                            В нашей компании вы можете выгодно застраховать свой автомобиль.
                            Менеджер поможет вам сориентироваться в тарифах и выбрать лучший
                        </p>
                        <button  type="button" data-toggle="modal" data-target="#bid" class="orange-button">
                            Отправить заявку
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="info-common-main-box">
            <div class="container">
            <div class="row">
                <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-12 info-common-main-title">
                    Наши преимущества
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-main-box-box">
                    <div class="info-common-main-box-image-bg-holder">
                        <img src="/img/icons/ic-01.png" style="position:relative; left: -7px;">
                    </div>
                    <div class="info-common-main-box-title">Заявка менеджеру</div>
                    <div class="info-common-main-box-text">Заполните данные и мы свяжемся с вами в течение 30 минут (с 09:00 до 21:00 без выходных).</div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-6 info-common-main-box-box">
                    <div class="info-common-main-box-image-bg-holder">
                        <img src="/img/icons/ic-09.png">
                    </div>
                    <div class="info-common-main-box-title">Страхование</div>
                    <div class="info-common-main-box-text">
                        Все виды страхования — осаго, каско, жизнь, имущество.
                        Различные варианты оплаты — франшиза, рассрочка, кредит.
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane fade row expertise" id="tab3">
        <div class="info-common-top-bg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-top-bg-left-text">
                        Экспертиза
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-top-bg-right-text">
                        <p>
                            Ежедневно в наш салон приезжают
                            технически и юридически проблемные
                            автомобили. За 8 лет работы, мы
                            научились видеть их насквозь
                        </p>
                        <button  type="button" data-toggle="modal" data-target="#bid" class="orange-button">
                            Отправить заявку
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="info-common-main-box">
            <div class="container">
                <div class="row">
                    <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-12 info-common-main-title">
                        Наши преимущества
                    </div>
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-main-box-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-13.png">
                        </div>
                        <div class="info-common-main-box-title">Техническая диагностика</div>
                        <div class="info-common-main-box-text">
                            В день мы проводим диагностику более 3
                            автомобилей разных марок и моделей.
                            Для этого в нашей компании работают лучшие
                            технические специалисты. Профессиональное
                            оборудование позволяет полностью проверить
                            абсолютно любой автомобиль. По результату проверки
                            вы получаете подробный диагностический лист со всеми
                            рекомендациями по обслуживанию.
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-main-box-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-12.png">
                        </div>
                        <div class="info-common-main-box-title">Юридическая проверка</div>
                        <div class="info-common-main-box-text">
                            Штат высококвалифицированных экспертов-криминалистов позволяет со 100%
                            уверенностью определить юридическую чистоту автомобиля.
                            Мы проверяем не только сам автомобиль и его документы,
                            но и его собственников, а также историю покупки.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div role="tabpanel" class="tab-pane fade row re-registration" id="tab4">
        <div class="info-common-top-bg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-top-bg-left-text">
                        Переоформление
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-top-bg-right-text">
                        <p>
                            Любые услуги "под ключ".
                        </p>
                        <button  type="button" data-toggle="modal" data-target="#bid" class="orange-button">
                            Отправить заявку
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="info-common-main-box">
            <div class="container">
                <div class="row">
                    <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-12 info-common-main-title">
                        Наши преимущества
                    </div>

                    <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-6 info-common-main-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-01.png" style="position:relative; left: -7px;">
                        </div>
                        <div class="info-common-main-box-title">Заявка менеджеру</div>
                        <div class="info-common-main-box-text">
                            Заполните данные и мы свяжемся с вами в течение 30 минут (с 09:00 до 21:00 без выходных).
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-sm-6 info-common-main-box">
                        <div class="info-common-main-box-image-bg-holder">
                            <img src="/img/icons/ic-18.png">
                        </div>
                        <div class="info-common-main-box-title">Любые услуги "под ключ"</div>
                        <div class="info-common-main-box-text">
                            Постановка на учет.
                            Заключение договора купли-продажи.
                            Перевес и сохранение номерных знаков.
                            Проверка денежных средств через кассу.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?= $this->render('partial/bid.phtml'); ?>
</services>
