<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 breadcrumbs">
            <a href="#" class="back">
                <span></span>
                <?= $this->translate('Каталог');?>
            </a>
        </div>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11">
            <div class="auto-card-title">
                <?= $this->translate("Skoda Rapid");?>
            </div>
            <div class="auto-card-price">
                <?= $this->translate("$6200");?>
            </div>
                <div class="jcarousel-wrapper">
                <div class="jcarousel">
                    <ul>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                    </ul>
                </div>
                <a href="#" class="jcarousel-control-prev"></a>
                <a href="#" class="jcarousel-control-next"></a>
            </div>
        </div>
    </div>
</div>
