<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 breadcrumbs">
            <a href="#" class="back">
                <span></span>
                <?= $this->translate('Каталог');?>
            </a>
        </div>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11">
            <div class="auto-card-title">
                <?= $this->translate("Skoda Rapid");?>
            </div>
            <div class="auto-card-price">
                <?= $this->translate("$6200");?>
            </div>
        </div>
    </div>
</div>
