<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 breadcrumbs">
            <a href="#" class="back">
                <span></span>
                <?= $this->translate('Каталог');?>
            </a>
        </div>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11">
            <div class="auto-card-title">
                <?= $this->translate("Skoda Rapid");?>
            </div>
            <div class="auto-card-price">
                <?= $this->translate("$6200");?>
            </div>
                <div class="jcarousel-wrapper">
                <div class="jcarousel">
                    <ul>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                        <li><img src="/img/bg-images/photo-5.png" width="487" height="350" alt=""></li>
                    </ul>
                </div>
                <a href="#" class="jcarousel-control-prev"></a>
                <a href="#" class="jcarousel-control-next"></a>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
    <div class="col-lg-offset-1 col-md-offset-1 col-lg-10 col-md-10 col-sm-12">
        <div class="auto-card-info-box">
            <div class="auto-card-info-title">
                <?= $this->translate("Технические характеристики");?>
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-5 auto-card-into-column">
                    <ul>
                        <li><span><?= $this->translate('Марка');?></span><?= $this->translate('Skoda');?></li>
                        <li><span><?= $this->translate('Модель');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Поколение');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Модификация');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Год');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Пробег');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Тип кузова');?></span><?= $this->translate('Rapid');?></li>
                    </ul>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-5 auto-card-into-column">
                    <ul>
                        <li><span><?= $this->translate('Цвет');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Тип двигателя');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Объем двигателя');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('КПП');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Привод');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Руль');?></span><?= $this->translate('Rapid');?></li>
                        <li><span><?= $this->translate('Мощность двигателя');?></span><?= $this->translate('Rapid');?></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="auto-card-info-box">
            <div class="auto-card-info-title">
                <?= $this->translate("Комплектация");?>
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-5 auto-card-into-column">
                    <ul>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                    </ul>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-5 auto-card-into-column">
                    <ul>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                        <li><?= $this->translate('Skoda');?></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="auto-card-info-box">
            <div class="auto-card-info-title">
                <?= $this->translate("Комплектация");?>
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-7 auto-card-into-text">
                    Был приобретен у официального дилера.
                    2 владельца, ПТС оригинал.
                    Дилерское обслуживание, в наличие сервисная книжка.
                </div>
            </div>
        </div>
    </div>
    </div>
</div>