<div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 breadcrumbs">
            <a href="#" class="back">
                <span></span>
                <?= $this->translate('Назад');?>
            </a>
        </div>
        <div class="col-lg-offset-1 col-md-offset-1 col-lg-11 col-md-11 catalog">
            <h2><?= $this->translate('Купить');?></h2>
            <div class="row catalog-filter-group">
                <div class="col-lg-5 col-md-5">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <label><?=$this->translate('Марка');?></label>
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <label><?=$this->translate('Модель');?></label>
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3">
                    <label><?=$this->translate('Год');?></label>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label><?=$this->translate('Цена');?></label>
                    <select>
                        <option value="1">One</option>
                    </select>
                </div>
                <div class="col-lg-2 col-md-2 no-label">
                    <select>
                        <option value="1">One</option>
                    </select>
                </div>
            </div>
            <div class="row catalog-filter-group">
                <div class="col-lg-5 col-md-5">
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <label><?=$this->translate('Поколение');?></label>
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <label><?=$this->translate('Кузов');?></label>
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <label><?=$this->translate('Двигатель');?></label>
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3">
                    <label><?=$this->translate('Мощность');?></label>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <select>
                                <option value="1">One</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label><?=$this->translate('Коробка');?></label>
                    <select>
                        <option value="1">One</option>
                    </select>
                </div>
                <div class="col-lg-2 col-md-2">
                    <label><?=$this->translate('Привод');?></label>
                    <select>
                        <option value="1">One</option>
                    </select>
                </div>
            </div>
            <div class="row catalog-filter-group-checkboxes">
                <div class="col-lg-5 col-md-5">
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <input type="checkbox">
                            <label><?=$this->translate('Со скидкой');?></label>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <input type="checkbox">
                            <label><?=$this->translate('Selected');?></label>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <input type="checkbox">
                            <label><?=$this->translate('Новые');?></label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7">
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <a href="javascript;:"></a>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <a href="javascript;:"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="grey-light-block offers-grid-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 catalog-offers-grid-block-title">
                <?= $this->translate('Каталог легковых автомобилей');?>
                <p>127 автомобилей</p>
            </div>
            <div class="col-lg-5 col-md-5 catalog-offers-grid-block-filter">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <select data-dropdown-options='{"customClass":"gray-dropdown"}'>
                            <option value="1">One</option>
                            <option value="1">One</option>
                            <option value="1">One</option>
                            <option value="1">One</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="offers-grid-block-grid">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 offers-grid-block-tile">
                            <a href="#" class="offers-grid-block-grid-bg">
                                <img src="" alt="">
                            </a>
                            <div href="#" class="offers-grid-block-grid-name">
                                <a href="#"><?= $this->translate('Skoda Rapid'); ?></a>
                                <br>
                                <span class="price">6200$</span>
                            </div>
                            <div class="offers-grid-block-grid-desc">
                                <?= $this->translate('2017, Дизель, 1.5 л, 90 л.с.,Механическая 5 ст., Универсал, передний привод'); ?>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 offers-grid-block-tile">
                            <a href="#" class="offers-grid-block-grid-bg">
                                <img src="" alt="">
                            </a>
                            <div href="#" class="offers-grid-block-grid-name">
                                <a href="#"><?= $this->translate('Skoda Rapid'); ?></a>
                                <br>
                                <span class="price">6200$</span>
                            </div>
                            <div class="offers-grid-block-grid-desc">
                                <?= $this->translate('2017, Дизель, 1.5 л, 90 л.с.,Механическая 5 ст., Универсал, передний привод'); ?>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 offers-grid-block-tile">
                            <a href="#" class="offers-grid-block-grid-bg">
                                <img src="" alt="">
                            </a>
                            <div href="#" class="offers-grid-block-grid-name">
                                <a href="#"><?= $this->translate('Skoda Rapid'); ?></a>
                                <br>
                                <span class="price">6200$</span>
                            </div>
                            <div class="offers-grid-block-grid-desc">
                                <?= $this->translate('2017, Дизель, 1.5 л, 90 л.с.,Механическая 5 ст., Универсал, передний привод'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="offers-grid-block-grid">
                <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 offers-grid-block-tile">
                            <a href="#" class="offers-grid-block-grid-bg">
                                <img src="" alt="">
                            </a>
                            <div href="#" class="offers-grid-block-grid-name">
                                <a href="#"><?= $this->translate('Skoda Rapid'); ?></a>
                                <br>
                                <span class="price">6200$</span>
                            </div>
                            <div class="offers-grid-block-grid-desc">
                                <?= $this->translate('2017, Дизель, 1.5 л, 90 л.с.,Механическая 5 ст., Универсал, передний привод'); ?>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 offers-grid-block-tile">
                            <a href="#" class="offers-grid-block-grid-bg">
                                <img src="" alt="">
                            </a>
                            <div href="#" class="offers-grid-block-grid-name">
                                <a href="#"><?= $this->translate('Skoda Rapid'); ?></a>
                                <br>
                                <span class="price">6200$</span>
                            </div>
                            <div class="offers-grid-block-grid-desc">
                                <?= $this->translate('2017, Дизель, 1.5 л, 90 л.с.,Механическая 5 ст., Универсал, передний привод'); ?>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 offers-grid-block-tile">
                            <a href="#" class="offers-grid-block-grid-bg">
                                <img src="" alt="">
                            </a>
                            <div href="#" class="offers-grid-block-grid-name">
                                <a href="#"><?= $this->translate('Skoda Rapid'); ?></a>
                                <br>
                                <span class="price">6200$</span>
                            </div>
                            <div class="offers-grid-block-grid-desc">
                                <?= $this->translate('2017, Дизель, 1.5 л, 90 л.с.,Механическая 5 ст., Универсал, передний привод'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>