<?php
/**
 * @var Dashboard\Entity\File $file
 * @var Application\Entity\Vehicle $item
 * @var Application\Entity\Options\Taxonomy $option
 * @var Zend\View\Renderer\PhpRenderer $this
 */
$this->headScript()->appendFile($this->basePath('js/index.js'));
foreach ($list as &$item) {
    $item['transparentImage'] = strval($this->basePath('/dashboard/img/trans.gif'));
    $item['link'] = $this->url('catalog', [
        'id' => $item['id'],
        'action' => 'card',
    ]);
}

?>
<script>var cardListInit = <?=json_encode($list);?>;</script>

<catalog inline-template>

<filter :card-list="cardList"></filter>

<div class="grey-light-block offers-grid-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-md-5 col-sm-8 col-xs-12 col-md-offset-1 catalog-offers-grid-block-title">
                <?= $this->translate('Каталог легковых автомобилей');?>
                <p>127 автомобилей</p>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12 catalog-offers-grid-block-filter">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-2 hidden-xs">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-10 col-xs-12">
                        <select data-dropdown-options='{"customClass":"gray-dropdown"}'>
                            <option value="1">One</option>
                            <option value="1">One</option>
                            <option value="1">One</option>
                            <option value="1">One</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-sm-12 col-xs-12 col-md-offset-1">
                <div v-if="cardList.length > 0" class="row">
                    <card
                        v-for="item in cardList"
                        v-bind:card="item"
                        v-bind:key="item.id">
                    </card>
                </div>
                <div v-else>
                    <div сlass="row">
                        <p class="catalog-no-result">
                            Поиск не дал результов.
                        </p>
                    </div>
                </div>
                <pagination
                        v-if="totalCards > 12"
                        :current="currentPage"
                        :total="totalCards"
                        :perPage="perPage"
                        @page-changed="fetchCards"
                ></pagination>
            </div>
        </div>
    </div>
</div>
</catalog>
