<?= $this->doctype() ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/header.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="" alt="Rudolf-autohaus"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" id="navbar-collapse">
                        <li class="dropdown-close-button">
                            <button type="button" class="close" data-toggle="collapse" data-target=".navbar-collapse">
                                &times;
                            </button>
                        </li>
                        <li class="dropdown-duplicate"><a href="#" class="active"><?= $this->translate('Купить');?></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?= $this->translate('Купить');?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#"><?= $this->translate('Легковые');?></a></li>
                                <li><a href="#"><?= $this->translate('Коммерческий транспорт');?></a></li>
                                <li><a href="#"><?= $this->translate('Мотоциклы');?></a></li>
                                <li><a href="#"><?= $this->translate('Подборки');?></a></li>
                            </ul>
                        </li>
                        <li><a href="#"><?= $this->translate('Продать');?></a></li>
                        <li><a href="#"><?= $this->translate('Услуги');?></a></li>
                        <li><a href="#"><?= $this->translate('Компания');?></a></li>
                        <li><a href="#"><?= $this->translate('Адреса салонов');?></a></li>
                    </ul>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-right-telephone hidden-sm hidden-xs"><a href="#">+38 063-123-45-67</a></li>
                    <li class="navbar-right-delimeter hidden-sm hidden-xs"></li>
                    <li><a href="#"><img width="30" height="30"></a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageCloseString('</li></ul></div>')
                    ->setMessageOpenFormat('<div%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><ul><li>')
                    ->setMessageSeparatorString('</li><li>');

                echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                echo $flash->render('zfcuser-login-form', array('alert', 'alert-dismissible', 'alert-danger'));
            ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
