<?php /** @var \Zend\View\Renderer\PhpRenderer $this */?>
<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <script type="text/javascript">
            var store = {
                nav : {
                    home:       { path: "/", name: 'home', text: "<?=$this->translate('Домой')?>"},
                    card:       { path: "<?= $this->url('card') ?>", name: 'card', text: "<?=$this->translate('Купить')?>"},
                    catalog:    { path: "<?= $this->url('catalog') ?>", name: 'catalog', text: "<?=$this->translate('Купить')?>"},
                    sale:       { path: "<?= $this->url('sale') ?>", name: 'sale', text: "<?=$this->translate('Продать')?>"},
                    services:   { path: "<?= $this->url('services') ?>", name: 'services', text: "<?=$this->translate('Услуги')?>"},
                    company:    { path: "<?= $this->url('company') ?>", name: 'company', text: "<?=$this->translate('Компания')?>"},
                    contacts:   { path: "<?= $this->url('contacts') ?>", name: 'contacts', text: "<?=$this->translate('Контакты')?>"},
                }
            };
        </script>
        <?= $this->headTitle('Rudolf AutoHaus')->setSeparator(' - ')
            ->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('theme-color', '#555963')
            ->appendName('msapplication-TileColor', '#ffffff')
            ->appendName('msapplication-TileImage', $this->basePath('icons/ms-icon-144x144.png'))
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

        <!-- Inline scripts -->
        <?php $this->inlineScript()
            ->prependFile($this->basePath('js/build.js'))
            ->prependFile($this->basePath('js/formstone/js/checkbox.js'))
//            ->prependFile($this->basePath('js/formstone/js/scrollbar.js'))
//            ->prependFile($this->basePath('js/formstone/js/dropdown.js'))
//            ->prependFile($this->basePath('js/formstone/js/touch.js'))
            ->prependFile($this->basePath('js/formstone/js/core.js'))
//            ->prependFile($this->basePath('js/jcarousel.skeleton.js'))
//            ->prependFile($this->basePath('js/jquery.jcarousel.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))?>

        <!-- Le styles -->
        <?= $this
            ->headLink(['rel' => 'icon', 'type' => 'image/png', 'sizes' => '16x16', 'href' => $this->basePath('icons/favicon-16x16.png')])
            ->headLink(['rel' => 'icon', 'type' => 'image/png', 'sizes' => '32x32', 'href' => $this->basePath('icons/favicon-32x32.png')])
            ->headLink(['rel' => 'icon', 'type' => 'image/png', 'sizes' => '96x96', 'href' => $this->basePath('icons/favicon-96x96.png')])
            ->headLink(['rel' => 'icon', 'type' => 'image/png', 'sizes' => '192x192', 'href' => $this->basePath('icons/android-icon-192x192.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '57x57', 'href' => $this->basePath('icons/apple-icon-57x57.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '60x60', 'href' => $this->basePath('icons/apple-icon-60x60.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '72x72', 'href' => $this->basePath('icons/apple-icon-72x72.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '76x76', 'href' => $this->basePath('icons/apple-icon-76x76.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '114x114', 'href' => $this->basePath('icons/apple-icon-114x114.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '120x120', 'href' => $this->basePath('icons/apple-icon-120x120.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '144x144', 'href' => $this->basePath('icons/apple-icon-144x144.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '152x152', 'href' => $this->basePath('icons/apple-icon-152x152.png')])
            ->headLink(['rel' => 'apple-touch-icon', 'sizes' => '180x180', 'href' => $this->basePath('icons/apple-icon-180x180.png')])

            ->headLink(['rel' => 'manifest', 'href' => $this->basePath('manifest.json')])

            ->prependStylesheet($this->basePath('css/main.css'))
            ->prependStylesheet($this->basePath('css/checkbox.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('js/formstone/css/checkbox.css'))
        ?>

        <script type="text/javascript">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-104493997-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <?php foreach ($list as &$item) {
        $item['link'] = $this->url('card', ['id' => $item['id']]);
        $item['transparentImage'] = strval($this->basePath('/dashboard/img/trans.gif'));
    } ?>
    <body>
        <script type="text/javascript">
            var cards = <?=json_encode($list);?>,
                categories = <?=json_encode($categories);?>;

                var cardListInit = [];
                for (var i in cards) {
                    cardListInit.push(cards[i]);
                }

            function initMap() {
                var uluru = { lat: 50.4451721, lng: 30.4881641 };
                var map = new google.maps.Map(document.getElementById('map'), { zoom: 15, center: uluru });
                var marker = new google.maps.Marker({ position: uluru, map: map });
            }
        </script>
        <div id="app">
            <app-navigation></app-navigation>
            <transition name="fade">
                <?= $this->content ?>
            </transition>
            <app-footer></app-footer>
            <app-order></app-order>
        </div>

        <?= $this->inlineScript() ?>
    </body>
</html>
