<!-- Карусель -->
<div id="top-carousel">
    <div class="container"><!-- Индикаторы для карусели -->
        <div class="row">
            <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1">
                <div class="title">
                    <?= $this->translate("Широкий выбор<br>автомобилей с пробегом");?>
                </div>
                <div class="undertitle">
                    <?= $this->translate("Все автомобили прошли полную диагностику, юридическую<br> проверку и предпродажную подготовку.")?>
                </div>
            </div>
        </div>
    </div>
</div>
<div>

<div class="list-auto container">
    <div class="row">
        <div class="title col-lg-offset-1 col-md-offset-1 col-sm-12 col-xs-12">
            <?= $this->translate("Выберите марку автомобиля");?>
        </div>
        <div>
            <!-- Навигация -->
            <div class="col-lg-offset-1 col-md-offset-1 col-sm-12 col-xs-12">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab"><?= $this->translate("Легковые автомобили");?></a></li>
                    <li><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><?=  $this->translate("Коммерческий транспорт");?></a></li>
                    <li><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab"><?= $this->translate("Мотоциклы");?></a></li>
                    <li><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab"><?= $this->translate("Подборки");?></a></li>
                </ul>
            </div>
            <!-- Содержимое вкладок -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6 col-lg-offset-1 col-md-offset-1">
                        <ul class="auto-list-list">
                            <li><a href="#">Audi</a><span>11</span></li>
                            <li><a href="#">Alfa Romeo</a><span>11</span></li>
                            <li><a href="#">BMW</a><span>11</span></li>
                            <li><a href="#">Bentley</a><span>11</span></li>
                            <li><a href="#">Cadillac</a><span>11</span></li>
                            <li><a href="#">Chery</a><span>11</span></li>
                            <li><a href="#">Chevrolet</a><span>11</span></li>
                            <li><a href="#">Chrysler</a><span>11</span></li>
                            <li><a href="#">Citroen</a><span>11</span></li>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-6">
                        <ul class="auto-list-list">
                            <li><a href="#">Audi</a><span>11</span></li>
                            <li><a href="#">Alfa Romeo</a><span>11</span></li>
                            <li><a href="#">BMW</a><span>11</span></li>
                            <li><a href="#">Bentley</a><span>11</span></li>
                            <li><a href="#">Cadillac</a><span>11</span></li>
                            <li><a href="#">Chery</a><span>11</span></li>
                            <li><a href="#">Chevrolet</a><span>11</span></li>
                            <li><a href="#">Chrysler</a><span>11</span></li>
                            <li><a href="#">Citroen</a><span>11</span></li>
                            <li><a href="#">Citroen</a><span>11</span></li>
                            <li><a href="#">Citroen</a><span>11</span></li>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-4 hidden-xs">
                        <ul class="auto-list-list">
                            <li><a href="#">Audi</a><span>11</span></li>
                            <li><a href="#">Alfa Romeo</a><span>11</span></li>
                            <li><a href="#">BMW</a><span>11</span></li>
                            <li><a href="#">Bentley</a><span>11</span></li>
                            <li><a href="#">Cadillac</a><span>11</span></li>
                            <li><a href="#">Chery</a><span>11</span></li>
                            <li><a href="#">Chevrolet</a><span>11</span></li>
                            <li><a href="#">Chevrolet</a><span>11</span></li>
                            <li><a href="#">Chevrolet</a><span>11</span></li>
                            <li><a href="#">Chrysler</a><span>11</span></li>
                            <li><a href="#">Citroen</a><span>11</span></li>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-2 hidden-sm hidden-xs">

                        <ul class="auto-list-list">
                            <li><a href="#">Audi</a><span>11</span></li>
                            <li><a href="#">Alfa Romeo</a><span>11</span></li>
                            <li><a href="#">BMW</a><span>11</span></li>
                            <li><a href="#">Bentley</a><span>11</span></li>
                            <li><a href="#">Cadillac</a><span>11</span></li>
                            <li><a href="#">Chery</a><span>11</span></li>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-2 hidden-sm hidden-xs">
                        <ul class="auto-list-list">
                            <li><a href="#">Audi</a><span>11</span></li>
                            <li><a href="#">Alfa Romeo</a><span>11</span></li>
                            <li><a href="#">BMW</a><span>11</span></li>
                            <li><a href="#">Bentley</a><span>11</span></li>
                            <li><a href="#">Cadillac</a><span>11</span></li>
                            <li><a href="#">Chery</a><span>11</span></li>
                            <li><a href="#">Chevrolet</a><span>11</span></li>
                            <li><a href="#">Chrysler</a><span>11</span></li>
                        </ul>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="profile"></div>
                <div role="tabpanel" class="tab-pane" id="messages"></div>
                <div role="tabpanel" class="tab-pane" id="settings"></div>
            </div>
        </div>
        <div class="hidden-lg hidden-md col-sm-12 col-xs-12">
            <button class="transparent-button all-auto-button">
                Все марки <span class="custom-caret"></span>
            </button>
        </div>
    </div>
</div>
<div class="offers">
    <div class="container">
    <div class="row">
        <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-lg-11 col-md-11 col-sm-11 col-xs-11">
            <p class="title"><?=$this->translate('Спецпредложения')?></p>
            <div class="slider">
                <div class="item">
                    <img src="">
                    <p class="name"><?= $this->translate('Fresh Moto');?></p>
                    <p class="desc"><?= $this->translate('Профессиональный подход <br>к мототехнике.');?></p>
                </div>
                <div class="item">
                    <img src="">
                    <p class="name"><?= $this->translate('Fresh Moto');?></p>
                    <p class="desc"><?= $this->translate('Профессиональный подход <br> к мототехнике.');?></p>
                </div>
                <div class="item">
                    <img src="">
                    <p class="name"><?= $this->translate('Fresh Moto');?></p>
                    <p class="desc"><?= $this->translate('Профессиональный подход <br> к мототехнике.');?></p>
                </div>
                <div class="item">
                    <img src="">
                    <p class="name"><?= $this->translate('Fresh Moto');?></p>
                    <p class="desc"><?= $this->translate('Профессиональный подход <br> к мототехнике.');?></p>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
